### ISSUE TITLE
Cant get to work

### ISSUE THREAD

**Issue by mola2alex** [myflashlab/speech-ANE#13]
Doesn't seem to like the manifest addition when compiling with Flash Pro CC and AIR 20.  I also clicked through to the commercial version but could not find it anywhere.

 <service android:name="com.doitflash.speech.speechToText.SpeechRecognitionService">

**Comment by mola2alex** [comment]
I would like to buy this extension but can't seem to find it on your page to add to the cart.  Still available?

**Comment by myflashlab** [comment]
Google has dropped support for the TTS and STT on the iOS side so we had to pull down the extension for now because only the Android side works now. you can contact us directly from http://myflashlab.com/contact/ if you have more questions
