### ISSUE TITLE
Cannot download ver 6.0

### ISSUE THREAD

**Issue by hengway1989** [myflashlab/speech-ANE#8]
Please help check issue as subject.
![screen shot 2015-08-21 at 10 17 53 am](https://cloud.githubusercontent.com/assets/13148479/9399952/eb41f0c0-47ed-11e5-9555-5cbaf67c4e0d.png)

Thank you

**Comment by myflashlab** [comment]
you're not receiving the download link at all or you are not receiving V6.0 link?

> If you have purchased the ANE in 2015 and you can’t see the new download links in the update manager page, Please drop us an email to get the latest version. if your purchase is older than 2015, you need to opt-in to the subscription plan.
